/* eslint-disable @typescript-eslint/no-unsafe-assignment */
/* eslint-disable @typescript-eslint/no-unsafe-member-access */
import {
  Injectable,
  NotFoundException,
  ConflictException,
  ForbiddenException,
  UnauthorizedException,
} from '@nestjs/common';
import { PrismaService } from './../../database/prisma.service';
import { UpdateUserDto } from './dto/update-user.dto';
import { CreateUserDto } from './dto/create-user.dto';
import { HashingUtil } from '../../common/utils/hashing.util';
import { UserRole, Prisma, AuditAction, AccountType, User } from '@prisma/client';
import { MailService } from '../mail/mail.service';
import { PasswordGeneratorUtil } from '../../common/utils/password-generator.util';
import { AuditLogsService } from '../audit-logs/audit-logs.service';
import { RegisterClientPersonalDto } from './dto/register-client-personal.dto';
import { RegisterClientBusinessDto } from './dto/register-client-business.dto';
import { RegisterSupplierDto } from './dto/register-supplier.dto';
import { RegisterSiteManagerDto } from './dto/register-site-manager.dto';
import { VendorRequestDto } from './dto/vendor-request.dto';
import { ReplyVendorRequestDto } from './dto/reply-vendor-request.dto';

interface RegistrationOptionalFields {
  accountType?: AccountType;
  businessName?: string;
  tinNumber?: string;
  businessCertificateDocument?: string;
  nationalIdDocument?: string;
}

type UserWithCompleteness = User & {
  isProfileComplete: boolean;
};

@Injectable()
export class UsersService {
  constructor(
    private readonly prisma: PrismaService,
    private readonly mailService: MailService,
    private readonly auditLogsService: AuditLogsService,
  ) {}

  async register(dto: CreateUserDto, createdByUserId?: string) {
    if (dto.role !== UserRole.CLIENT && !createdByUserId) {
      throw new UnauthorizedException(
        `Registration for ${dto.role} requires an administrator token.`,
      );
    }

    if (createdByUserId) {
      const creator = await this.prisma.user.findUnique({
        where: { id: createdByUserId },
        select: { role: true, siteId: true, isActive: true, deletedAt: true },
      });

      if (!creator || creator.deletedAt || !creator.isActive) {
        throw new ForbiddenException('Invalid creator account');
      }

      this.validateUserCreation(creator.role, dto.role, creator.siteId, dto.siteId);
    }

    const existingUser = await this.prisma.user.findFirst({
      where: {
        OR: [{ email: dto.email }, { phone: dto.phone }],
        deletedAt: null,
      },
    });

    if (existingUser) {
      throw new ConflictException('Email or phone number already in use');
    }

    let passwordToHash = dto.password;
    const isAutoGenerated = !passwordToHash;

    if (isAutoGenerated) {
      passwordToHash = PasswordGeneratorUtil.generate(12);
    }

    // Always send credentials email if password was auto-generated OR if an admin created the user
    if (isAutoGenerated || createdByUserId) {
      await this.mailService.sendPasswordEmail(dto.email, passwordToHash, dto.role);
    }
    const hashedPassword = await HashingUtil.hash(passwordToHash);

    const extraFields = dto as RegistrationOptionalFields;

    const user = await this.prisma.user.create({
      data: {
        email: dto.email,
        password: hashedPassword,
        firstName: dto.firstName,
        lastName: dto.lastName,
        phone: dto.phone,
        role: dto.role,
        siteId: dto.siteId || null,
        isActive: true,
        accountType:
          ((extraFields as any).accountType as unknown as AccountType) ||
          (dto.role === UserRole.CLIENT ? AccountType.PERSONAL : (null as any)),
        businessName: (extraFields as any).businessName || null,
        tinNumber: (extraFields as any).tinNumber || null,
        businessCertificateDocument: (extraFields as any).businessCertificateDocument || null,
        nationalIdDocument: (extraFields as any).nationalIdDocument || null,
      } as any,
    });

    // Update completeness after creation (fields are now in user object)
    const isComplete = this.determineProfileCompleteness(user as unknown as UserWithCompleteness);
    await this.prisma.user.update({
      where: { id: user.id },
      data: { isProfileComplete: isComplete } as Prisma.UserUpdateInput,
    });

    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    const { password: p, refreshToken, deletedAt, ...userWithoutSensitiveData } = user;

    await this.auditLogsService.createAuditLog(
      createdByUserId || user.id,
      AuditAction.CREATE,
      'USER',
      user.id,
      { email: user.email, role: user.role },
    );

    return {
      status: 'success',
      message: 'User registered successfully.',
      data: { ...userWithoutSensitiveData, isProfileComplete: isComplete },
    };
  }

  private determineProfileCompleteness(user: UserWithCompleteness): boolean {
    const commonFields: (keyof UserWithCompleteness)[] = [
      'email',
      'firstName',
      'lastName',
      'phone',
      'password',
    ];
    const hasCommonFields = commonFields.every((field) => !!user[field]);

    if (!hasCommonFields) return false;

    // siteId check (Required for all except SUPER_ADMIN)
    if (user.role !== UserRole.SUPER_ADMIN && !user.siteId) {
      return false;
    }

    if (user.role === UserRole.CLIENT) {
      if (user.accountType === AccountType.BUSINESS) {
        return !!(
          user.businessName &&
          user.tinNumber &&
          user.businessCertificateDocument &&
          user.nationalIdDocument
        );
      }
      return !!user.nationalIdDocument;
    }

    if (user.role === UserRole.SUPPLIER) {
      return !!(
        user.businessName &&
        user.tinNumber &&
        user.businessCertificateDocument &&
        user.nationalIdDocument
      );
    }

    if (user.role === UserRole.SITE_MANAGER) {
      return true; // siteId already checked
    }

    if (user.role === UserRole.SUPER_ADMIN) {
      return true;
    }

    return false;
  }

  async getProfileCompleteness(userId: string) {
    const user = await this.prisma.user.findUnique({
      where: { id: userId },
    });

    if (!user) {
      throw new NotFoundException('User not found');
    }

    const isComplete = this.determineProfileCompleteness(user as UserWithCompleteness);

    // Sync field if it was somehow out of sync
    if ((user as UserWithCompleteness).isProfileComplete !== isComplete) {
      await this.prisma.user.update({
        where: { id: userId },
        data: { isProfileComplete: isComplete } as Prisma.UserUpdateInput,
      });
    }

    return {
      isProfileComplete: isComplete,
      role: user.role,
      missingFields: this.getMissingFields(user as UserWithCompleteness),
    };
  }

  private getMissingFields(user: UserWithCompleteness): string[] {
    const missing: string[] = [];
    const commonFields: (keyof UserWithCompleteness)[] = [
      'email',
      'firstName',
      'lastName',
      'phone',
      'password',
    ];
    commonFields.forEach((f) => {
      if (!user[f]) missing.push(f as string);
    });

    if (user.role !== UserRole.SUPER_ADMIN && !user.siteId) {
      missing.push('siteId');
    }

    if (user.role === UserRole.CLIENT) {
      if (user.accountType === AccountType.BUSINESS) {
        if (!user.businessName) missing.push('businessName');
        if (!user.tinNumber) missing.push('tinNumber');
        if (!user.businessCertificateDocument) missing.push('businessCertificateDocument');
        if (!user.nationalIdDocument) missing.push('nationalIdDocument');
      } else if (!user.nationalIdDocument) missing.push('nationalIdDocument');
    }

    if (user.role === UserRole.SUPPLIER) {
      if (!user.businessName) missing.push('businessName');
      if (!user.tinNumber) missing.push('tinNumber');
      if (!user.businessCertificateDocument) missing.push('businessCertificateDocument');
      if (!user.nationalIdDocument) missing.push('nationalIdDocument');
    }

    return missing;
  }

  async registerClientPersonal(dto: RegisterClientPersonalDto, nationalIdUrl?: string) {
    const registerDto: CreateUserDto & RegistrationOptionalFields = {
      ...dto,
      role: UserRole.CLIENT,
      nationalIdDocument: nationalIdUrl,
      accountType: dto.accountType as AccountType,
    };
    return this.register(registerDto as CreateUserDto);
  }

  async registerClientBusiness(
    dto: RegisterClientBusinessDto,
    businessCertificateUrl?: string,
    nationalIdUrl?: string,
  ) {
    const registerDto: CreateUserDto & RegistrationOptionalFields = {
      ...dto,
      role: UserRole.CLIENT,
      accountType: AccountType.BUSINESS,
      businessCertificateDocument: businessCertificateUrl,
      nationalIdDocument: nationalIdUrl,
    };
    return this.register(registerDto as CreateUserDto);
  }

  async registerSupplier(
    dto: RegisterSupplierDto,
    businessCertificateUrl?: string,
    nationalIdUrl?: string,
    createdByUserId?: string,
  ) {
    const registerDto: CreateUserDto & RegistrationOptionalFields = {
      ...dto,
      role: UserRole.SUPPLIER,
      businessCertificateDocument: businessCertificateUrl,
      nationalIdDocument: nationalIdUrl,
      accountType: (dto.accountType as AccountType) || AccountType.BUSINESS,
    };
    return this.register(registerDto as CreateUserDto, createdByUserId);
  }

  async registerSiteManager(dto: RegisterSiteManagerDto, createdByUserId?: string) {
    const registerDto: CreateUserDto & RegistrationOptionalFields = {
      ...dto,
      role: UserRole.SITE_MANAGER,
      accountType: dto.accountType as AccountType,
    };
    return this.register(registerDto as CreateUserDto, createdByUserId);
  }

  async createVendorRequest(dto: VendorRequestDto) {
    const request = await this.prisma.vendorRequest.create({
      data: dto as unknown as Prisma.VendorRequestCreateInput,
    });
    return {
      status: 'success',
      message: 'Vendor request submitted successfully.',
      data: request,
    };
  }

  async findAllVendorRequests() {
    const requests = await this.prisma.vendorRequest.findMany({
      where: { deletedAt: null },
      orderBy: { createdAt: 'desc' },
    });
    return {
      status: 'success',
      data: requests,
    };
  }

  async replyToVendorRequest(dto: ReplyVendorRequestDto) {
    const request = await this.prisma.vendorRequest.findFirst({
      where: { email: dto.email, deletedAt: null } as Prisma.VendorRequestWhereInput,
      orderBy: { createdAt: 'desc' },
    });

    if (!request) {
      throw new NotFoundException(`Vendor request with email ${dto.email} not found`);
    }

    const updatedRequest = await this.prisma.vendorRequest.update({
      where: { id: request.id },
      data: {
        replyMessage: dto.message,
        status: 'APPROVED',
      },
    });

    // Send email to the vendor
    await this.mailService.sendEmail(request.email, 'Reply to your Vendor Request', dto.message);

    return {
      status: 'success',
      message: 'Reply sent successfully.',
      data: updatedRequest,
    };
  }

  private validateUserCreation(
    creatorRole: UserRole,
    newUserRole: UserRole,
    creatorSiteId: string | null,
    newUserSiteId: string | null,
  ) {
    if (creatorRole === UserRole.SUPER_ADMIN) return;

    if (creatorRole === UserRole.SITE_MANAGER) {
      const allowedRoles: UserRole[] = [UserRole.SUPPLIER, UserRole.CLIENT];

      if (!allowedRoles.includes(newUserRole)) {
        throw new ForbiddenException('Site managers can only register suppliers and clients');
      }
      if (creatorSiteId !== newUserSiteId) {
        throw new ForbiddenException('Site managers can only register users for their own site');
      }
      return;
    }

    throw new ForbiddenException('You do not have permission to register users');
  }

  async update(id: string, dto: UpdateUserDto, requesterId: string) {
    const requester = await this.prisma.user.findUnique({
      where: { id: requesterId },
      select: { role: true, siteId: true },
    });

    if (!requester) {
      throw new UnauthorizedException('User not found');
    }

    const { data: targetUser } = await this.findOne(id);

    if (requester.role === UserRole.SITE_MANAGER) {
      if (targetUser.siteId !== requester.siteId) {
        throw new ForbiddenException('You can only update users in your site');
      }
      if (dto.role && dto.role !== targetUser.role) {
        throw new ForbiddenException('Site managers cannot change user roles');
      }
    }

    if (dto.role === UserRole.SUPER_ADMIN && requester.role !== UserRole.SUPER_ADMIN) {
      throw new ForbiddenException('Cannot promote users to SUPER_ADMIN');
    }

    const { password, accountType, ...otherData } = dto;
    const updateData: Prisma.UserUpdateInput = { ...otherData };

    if (accountType) {
      updateData.accountType = accountType as unknown as AccountType;
    }

    if (password) {
      updateData.password = await HashingUtil.hash(password);
    }

    const updatedUser = await this.prisma.user.update({
      where: { id },
      data: updateData,
    });

    // Re-calculate completeness after update
    const isComplete = this.determineProfileCompleteness(updatedUser as UserWithCompleteness);
    if ((updatedUser as UserWithCompleteness).isProfileComplete !== isComplete) {
      await this.prisma.user.update({
        where: { id },
        data: { isProfileComplete: isComplete } as Prisma.UserUpdateInput,
      });
      (updatedUser as UserWithCompleteness).isProfileComplete = isComplete;
    }

    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    const { password: p, refreshToken: r, ...data } = updatedUser;

    await this.auditLogsService.createAuditLog(requesterId, AuditAction.UPDATE, 'USER', id, {
      updatedFields: Object.keys(otherData),
    });

    return { status: 'success', data };
  }

  async findAll(requesterId: string) {
    const requester = await this.prisma.user.findUnique({
      where: { id: requesterId },
      select: { role: true, siteId: true },
    });

    if (!requester) {
      throw new UnauthorizedException('User not found');
    }

    const where: Prisma.UserWhereInput = { deletedAt: null };

    if (requester.role === UserRole.SITE_MANAGER && requester.siteId) {
      where.siteId = requester.siteId;
    }

    return {
      status: 'success',
      data: await this.prisma.user.findMany({ where }),
    };
  }

  async findOne(id: string) {
    const user = await this.prisma.user.findFirst({
      where: { id, deletedAt: null },
      include: { site: true },
    });
    if (!user) throw new NotFoundException('User not found');
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    const { password, refreshToken, ...data } = user;
    return { status: 'success', data };
  }

  async remove(id: string, requesterId: string) {
    const requester = await this.prisma.user.findUnique({
      where: { id: requesterId },
      select: { role: true, siteId: true },
    });

    if (!requester) {
      throw new UnauthorizedException('User not found');
    }

    const { data: user } = await this.findOne(id);

    if (requester.role === UserRole.SITE_MANAGER) {
      if (user.siteId !== requester.siteId) {
        throw new ForbiddenException('You can only delete users in your site');
      }
    }

    return this.prisma.$transaction(async (tx) => {
      await tx.otp.deleteMany({ where: { userId: id } });

      if (user.role === UserRole.SITE_MANAGER && user.siteId) {
        await tx.site.update({
          where: { id: user.siteId },
          data: { managerId: null },
        });
      }

      await tx.user.update({
        where: { id },
        data: {
          deletedAt: new Date(),
          isActive: false,
          refreshToken: null,
        },
      });

      await this.auditLogsService.createAuditLog(requesterId, AuditAction.DELETE, 'USER', id, {
        reason: 'Soft deleted',
      });

      return { status: 'success', message: 'User soft deleted' };
    });
  }
}
